CREATE TABLE emprunts (
    ID INT(11) NOT NULL AUTO_INCREMENT,
    Utilisateur_ID INT(11) DEFAULT NULL,
    Livre_ID INT(11) DEFAULT NULL,
    DateEmprunt DATE DEFAULT NULL,
    DateEcheance DATE DEFAULT NULL,
    Retard TINYINT(1) DEFAULT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE livres (
    ID INT(11) NOT NULL AUTO_INCREMENT,
    Titre VARCHAR(255) DEFAULT NONE,
    Auteur VARCHAR(255) DEFAULT NULL,
    Categorie VARCHAR(100) DEFAULT NULL,
    Etat VARCHAR(50) DEFAULT NULL,
    PRIMARY KEY (ID)
);